import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Recipe Finder Application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <header className="flex justify-between items-center p-4  mb-8 ">
          <div className="text-2xl font-bold">
            <Link href="/" className="hover:text-gray-400">Recipe Finder Application</Link>
          </div>
        </header>
        <main className="mx-auto w-[80%]">
          {children}
        </main>
      </body>
    </html>
  );
}
